src/beans/User.java
package beans;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;

    private static Map<Integer, String> branches = new HashMap<>();
    private static Map<Integer, String> departments = new HashMap<>();

    static {
    	branches.put(1, "本社");
    	branches.put(2, "福岡支店");
    	branches.put(100, "大阪支店");
    	branches.put(102, "名古屋支店");
    	branches.put(105, "北海道支店");
    	branches.put(112, "仙台支店");

    	departments.put(1, "総務");
    	departments.put(2, "支店長");
    	departments.put(103, "係長");
    	departments.put(100, "平社員");
    	departments.put(102, "派遣社員");
    	departments.put(106, "課長");
    	departments.put(107, "バイト");
    }

    public static Map<Integer, String> getBranches() {
    	return branches;
    }

    public static Map<Integer, String> getDepartments() {
    	return departments;
    }

    private int id;
    private String userid;
    private String password;
    private String passwordconfirm;
    private String name;
    private int branchnumber;
    private int departmentnumber;

    public String getBranchName() {
    	return branches.get(branchnumber);
    }
    public String getDepartmentName() {
    	return departments.get(departmentnumber);
    }
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getUserId() {
		return userid;
	}
	public void setUserId(String userid) {
		this.userid = userid;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getPasswordConfirm() {
		return passwordconfirm;
	}
	public void setPasswordConfirm(String passwordconfirm) {
		this.passwordconfirm = passwordconfirm;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getBranchNumber() {
		return branchnumber;
	}
	public void setBranchNumber(int branchnumber) {
		this.branchnumber = branchnumber;
	}
	public int getDepartmentNumber() {
		return departmentnumber;
	}
	public void setDepartmentNumber(int departmentnumber) {
		this.departmentnumber = departmentnumber;
	}
}

src/controller/ManageServlet.java
package controller;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/manage" })

public class ManageServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		UserService service = new UserService();
		List<User> users = service.getUsers();
		request.setAttribute("users", users);
		request.getRequestDispatcher("manage.jsp").forward(request, response);
	}

}

src/controller/SettingServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/setting" })
public class SettingServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws ServletException, IOException {

    	Integer id = Integer.parseInt(request.getParameter("id"));

        User editUser = new UserService().getUser(id);
        request.setAttribute("editUser", editUser);
    	request.setAttribute("branches", User.getBranches());
    	request.setAttribute("departments", User.getDepartments());

        request.getRequestDispatcher("setting.jsp").forward(request, response);
    }

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		List<String> messages = new ArrayList<>();
		User editUser = getEditUser(request);

		if (isValid(request, messages) == true) {
			new UserService().update(editUser);
			response.sendRedirect("./");
			return;
		}
		request.setAttribute("errorMessages", messages);
		request.setAttribute("editUser", editUser);
    	request.setAttribute("branches", User.getBranches());
    	request.setAttribute("departments", User.getDepartments());

		request.getRequestDispatcher("setting.jsp").forward(request, response);
	}

	private User getEditUser(HttpServletRequest request)
			throws IOException, ServletException {

		User editUser = new User();
		editUser.setId(Integer.parseInt(request.getParameter("id")));
		editUser.setName(request.getParameter("name"));
		editUser.setUserId(request.getParameter("userid"));
		editUser.setPassword(request.getParameter("password"));
		editUser.setPasswordConfirm(request.getParameter("passwordconfirm"));
		editUser.setBranchNumber(Integer.parseInt(request.getParameter("branchnumber")));
		editUser.setDepartmentNumber(Integer.parseInt(request.getParameter("departmentnumber")));
		return editUser;
	}


	private boolean isValid(HttpServletRequest request, List<String> messages) {

		String account = request.getParameter("userid");
		String password = request.getParameter("password");
		String passwordconfirm = request.getParameter("passwordconfirm");

		if (StringUtils.isEmpty(account) == true) {
			messages.add("アカウント名を入力してください");
		}
		if (StringUtils.isEmpty(password) == true) {
			messages.add("パスワードを入力してください");
		}
		if (!password.equals(passwordconfirm)) {
			messages.add("パスワードを入力してください");
		}
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/SignUpServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

    	request.setAttribute("branches", User.getBranches());
    	request.setAttribute("departments", User.getDepartments());

        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        List<String> messages = new ArrayList<>();
        User user = new User();
        user.setName(request.getParameter("name"));
        user.setUserId(request.getParameter("userid"));
        user.setPassword(request.getParameter("password"));
        user.setPasswordConfirm(request.getParameter("passwordconfirm"));
        user.setBranchNumber(Integer.parseInt(request.getParameter("branchnumber")));
        user.setDepartmentNumber(Integer.parseInt(request.getParameter("departmentnumber")));

        if (isValid(request, messages) == true) {
            new UserService().register(user);

            response.sendRedirect("./");
            return;
        }

        request.setAttribute("user", user);
        request.setAttribute("errorMessages", messages);
    	request.setAttribute("branches", User.getBranches());
    	request.setAttribute("departments", User.getDepartments());
        request.getRequestDispatcher("signup.jsp").forward(request, response);
    }

    private boolean isValid(HttpServletRequest request, List<String> messages) {
        String userid = request.getParameter("userid");
        String password = request.getParameter("password");
		String passwordconfirm = request.getParameter("passwordconfirm");
        String name = request.getParameter("name");

        if (StringUtils.isEmpty(name)) {
            messages.add("ユーザー名を入力してください");
        }
        if (name.length() >10) {
        	messages.add("ユーザー名は10文字以内で入力してください");
        }

        if (StringUtils.isEmpty(userid)) {
        	messages.add("ログインIDを入力してください");
        }
        if (!userid.matches("\\w{6,20}")) {
        	messages.add("ログインIDは半角英数字6文字以上20文字以下で入力してください");
        }
        if (StringUtils.isEmpty(password)) {
        	messages.add("パスワードを入力してください");
        }
        if (!password.matches("^[a-zA-Z0-9 -/:-@\\[-\\`\\{-\\~]+${6,20}")) {
        	messages.add("パスワードは記号を含む全ての半角英数字6文字以上20文字以下で入力してください");
        }
        if (!password.equals(passwordconfirm)) {
        	messages.add("パスワードが違います");
        }

        if (name.length() > 11) {
        	messages.add("名前のフォーマットが不正です");
        }

        return messages.size() == 0;
    }
}

src/controller/TopServlet.java
package controller;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(urlPatterns = { "/index.jsp" })
public class TopServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response) throws IOException, ServletException {

        request.getRequestDispatcher("/top.jsp").forward(request, response);
    }
}

WebContent/login.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ログイン</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">

			<c:if test="${ not empty errorMessages }">
				<div class="errorMessages">
					<ul>
						<c:forEach items="${errorMessages}" var="message">
							<li><c:out value="${message}" />
						</c:forEach>
					</ul>
				</div>
				<c:remove var="errorMessages" scope="session"/>
			</c:if>

			<form action="login" method="post"><br />
				<label for="accountOrEmail">アカウント名かメールアドレス</label>
				<input name="accountOrEmail" id="accountOrEmail"/> <br />

				<label for="password">パスワード</label>
				<input name="password" type="password" id="password"/> <br />

				<input type="submit" value="ログイン" /> <br /><br />
				<a href="./">戻る</a>
			</form>
			<div class="copylight"> Copyright(c)YourName</div>
		</div>
	</body>
</html>

WebContent/manage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>ユーザー管理画面</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
<body>
			<div>
				<c:if test="${ empty loginUser }">
					<a href="signup">登録する</a><br/><br/>
					<a href="edit">ユーザー編集画面</a>
				</c:if>
			</div>

			<table>
				<tr>
					<th>名前</th>
					<th>ログインID</th>
					<th>支店</th>
					<th>部署・役職</th>
					<th></th>
				</tr>
				<c:forEach items="${users}" var="user">
					<tr>
						<td><a href="setting?id=${user.id}">${user.name}</a></td>
						<td>${user.userId}</td>
						<td>${user.branchName}</td>
						<td>${user.departmentName}</td>
						<td>
							<form action="delete" method="POST">
								<input type="hidden" name="id" value="${user.id}">
								<input type="submit" value="削除" />
							</form>
						</td>
					</tr>
				</c:forEach>
			</table>
</body>
</html>

WebContent/setting.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>${loginUser.account}の設定</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="main-contents">

            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if>

            <form action="setting" method="post"><br />
                <input name="id" value="${editUser.id}" id="id" type="hidden"/>
                <label for="name">名前</label>
                <input name="name" value="${editUser.name}" id="name"/>（名前はあなたの公開プロフィールに表示されます）<br />

                <label for="userid">ログインID</label>
                <input name="userid" value="${editUser.userId}" id="userid" /><br />

                <label for="password">パスワード</label>
                <input name="password" type="password" id="password"/> <br />
                <label for="passwordconfirm">確認用パスワード (上記のパスワードをコピーせずに記入ください。)</label>
                <input name="passwordconfirm" type="password" id="passwordconfirm" />

                <label for="branchnumber">支店</label>
                <select name="branchnumber" id="branchnumber">
                	<c:forEach items="${branches}" var="branchnumber">
                		<option value="${branchnumber.key}" <c:if test='${editUser.branchNumber==branchnumber.key}'>selected</c:if>>${branchnumber.value}</option>
                	</c:forEach>
                </select> <br />

                 <label for="departmentnumber">役職</label>
                    <select name="departmentnumber" id="departmentnumber">
                		<c:forEach items="${departments}" var="departmentnumber">
                			<option value="${departmentnumber.key}" <c:if test='${editUser.departmentNumber==departmentnumber.key}'>selected</c:if>>${departmentnumber.value}</option>
                		</c:forEach>
                	</select>


                <input type="submit" value="登録" /> <br />
                <a href="./">戻る</a>
            </form>
            <div class="copyright"> Copyright(c)Your Name</div>
        </div>
    </body>
</html>

WebContent/signup.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
	<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー新規登録</title>
</head>
<body>
	<div class="main-contents">
		<c:if test="${not empty errorMessages}">
			<div class="errorMessages">
				<ul>
					<c:forEach items="${errorMessages}" var="message">
						<li><c:out value="${message}" />
					</c:forEach>
				</ul>
			</div>
			<c:remove var="errorMessages" scope="session" />
		</c:if>
		<br /> ユーザー新規登録<br />
		<form action="signup" method="post">
			<br />
		    <label for="name">ユーザー名(10文字以内)</label>
		    <br />
		    <input type="text" name="name" id="name" size="20" />
		    <br />
		    <label for="branchnumber">支店コード</label>
		    <br />
		    <select name="branchnumber">
                	<c:forEach items="${branches}" var="branch">
                		<option value="${branch.key}" <c:if test='${user.branchNumber==branch.key}'>selected</c:if>>${branch.value}</option>
                	</c:forEach>
                </select>
		    <br />
		    <label for="departmentnumber">部署（役職）コード</label>
		    <br />
		   <select name="departmentnumber">
                		<c:forEach items="${departments}" var="department">
                			<option value="${department.key}" <c:if test='${user.departmentNumber==department.key}'>selected</c:if>>${department.value}</option>
                		</c:forEach>
                	</select>
		    <br />
			<label for="userid">ログインID（半角英数字6文字以上20文字以下）</label>
			<br />
			<input type="text" name="userid" size="25" id="userid" />
			<br />
			<label for="password">パスワード（記号を含む全ての半角数字6文字以上20文字以下）</label>
			<br />
			<input type="password" name="password" id="password" size="25" />
			<br />
			<label for="passwordconfirm">パスワード（確認用）</label>
			<br />
			<input type="password" name="passwordconfirm" id="passwordconfirm" size="25" />
			<br />
			<br />
			<input type="submit" value="登録" />
			<br />
			<a href="./">戻る</a>
		</form>
	</div>
</body>
</html>

WebContent/top.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>簡易掲示板</title>
		<link href="./css/style.css" rel="stylesheet" type="text/css">
	</head>
	<body>
		<div class="main-contents">
			<div class="header">
				<c:if test="${ empty loginUser }">
					<a href="login">ログイン</a>
					<a href="signup">登録する</a>
					<a href="manage">ユーザー管理画面</a>
				</c:if>
				<c:if test="${ not empty loginUser }">
					<a href="./">ホーム</a>
					<a href="setting">設定</a>
					<a href="logout">ログアウト</a>
				</c:if>
			</div>

			<c:if test="${ not empty loginUser }">
			    <div class="profile">
			        <div class="name"><h2><c:out value="${loginUser.name}" /></h2></div>
			        <div class="account">
			            @<c:out value="${loginUser.account}" />
			        </div>
			        <div class="account">
			            <c:out value="${loginUser.description}" />
			        </div>
			    </div>
			</c:if>
			</div>
			<div class="copylight"> Copyright(c)YourName</div>
	</body>
</html>